### ISSUE TITLE
It crashes my modem

### ISSUE THREAD

**Issue by Gavergracht** [nimroddolev/akuvox#83]
### System Health details

System is ok

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nimroddolev/akuvox/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When I install the integration, my modem restarts every 5 minutes

### Reproduction steps

1. Install integration
2. Crash after x minutes of modem (restarts)
3. After removing integration and restarting Ha, everything is ok
...

### Debug logs

```text
I get a lot of errors :slight_smile: 



Logger: homeassistant.components.stream.stream.camera.praktijk
Bron: components/stream/__init__.py:448
integratie: Stream (documentatie, problemen)
Eerst voorgekomen: 07:05:17 (12 gebeurtenissen)
Laatst gelogd: 07:17:09

Error from stream worker: Error opening stream (INVALIDDATA, Invalid data found when processing input, rtsp://****:****@52.58.161.16:554/0C11051E0A89)
Error from stream worker: Error opening stream (ERRORTYPE_113, Host is unreachable, rtsp://****:****@52.58.161.16:554/0C11051E0A89)
Error from stream worker: Error opening stream (ERRORTYPE_110, Operation timed out, rtsp://****:****@52.58.161.16:554/0C11051E0A89)

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.akuvox
Bron: custom_components/akuvox/api.py:656
integratie: Akuvox SmartPlus (documentatie, problemen)
Eerst voorgekomen: 07:05:34 (1 gebeurtenissen)
Laatst gelogd: 07:05:34

Timeout occured for 'app/single' API get request: https://ecloud.akuvox.com/web-server/v3/app/single/log/getDoorLog?row=1

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.akuvox
Bron: custom_components/akuvox/api.py:107
integratie: Akuvox SmartPlus (documentatie, problemen)
Eerst voorgekomen: 07:03:44 (1 gebeurtenissen)
Laatst gelogd: 07:03:44

📜 Regional API subdomain not configured...using pre v0.0.7 backward compatible 'ecloud'

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.akuvox
Bron: custom_components/akuvox/api.py:650
integratie: Akuvox SmartPlus
Eerst voorgekomen: 07:05:24 (1 gebeurtenissen)
Laatst gelogd: 07:05:24

Timeout occured for 'app/community' API get request: https://ecloud.akuvox.com/web-server/v3/app/community/log/getDoorLog?row=1 - Retry using 'single'...

Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant
Bron: custom_components/akuvox/api.py:658
integratie: Akuvox SmartPlus
Eerst voorgekomen: 07:05:34 (1 gebeurtenissen)
Laatst gelogd: 07:05:34

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/akuvox/api.py", line 642, in _api_wrapper
    response = await self.hass.async_add_executor_job(func, url, headers, data, 10)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/akuvox/api.py", line 638, in _api_wrapper
    async with async_timeout.timeout(10):
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/akuvox/api.py", line 582, in async_retrieve_personal_door_log
    json_data = await self.async_get_personal_door_log()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/akuvox/api.py", line 616, in async_get_personal_door_log
    json_data = await self._api_wrapper(method="get", url=url, headers=headers, data=data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/akuvox/api.py", line 654, in _api_wrapper
    return await self._api_wrapper(method, url, data, headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/akuvox/api.py", line 658, in _api_wrapper
    raise AkuvoxApiClientCommunicationError(
custom_components.akuvox.api.AkuvoxApiClientCommunicationError: Timeout error fetching information:
```

**Comment by benjamincamillenana** [comment]
Hello

I have the same problem 
Have you find a solution ?
thanks

**Comment by Gavergracht** [comment]
i use webhook /http commands to open the door when buzzed. i did not get the akuvox integration running....Op 7 dec. 2024 09:31 schreef benjamincamillenana ***@***.***>:
Hello
I have the same problem
Have you find a solution ?
thanks

**Comment by benjamincamillenana** [comment]
Ok thanks but i'm new on HA 
Do you have a documentation or link for this integration ?
thanks for your help

**Comment by benjamincamillenana** [comment]
I have find somethings
when i remove the network connection of my indoor intercom, the HA and my box work correctly
I continue to search :)
